#!/bin/bash
if (($# != 4));then
echo "Need 4 args"
exit
fi
if (($3 == 1));then
for ((i=1; i<=$1; i++))
do
for ((j=1; j<=$2; j++))
do
echo -n $4
done
echo ""
done
elif(($3 == 0));then
for ((i=1; i<=$1; i++))
do
echo -n $4
for ((j=2; j<=$2-1; j++))
do
if ((i != 1 && i!= $1));then
VAR=$4
VAR_LENGTH=${#VAR}
for ((k=0; k<VAR_LENGTH; k++))
do
echo -n " "
done
else
echo -n $4
fi
done
echo "$4"
done
fi
